# SearXNG Configuration - Optimized for API performance
general:
  debug: false
  instance_name: "DeepSearch SearXNG"
  enable_metrics: false
  enable_health_check: true

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "your-secret-key-here"
  base_url: false
  image_proxy: false
  http_protocol_version: "1.0"
  method: "POST"
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

ui:
  static_path: ""
  templates_path: ""
  default_theme: simple
  default_locale: "en"
  results_on_new_tab: false
  infinite_scroll: false

engines:
  - name: google
    engine: google
    shortcut: g
    timeout: 3.0
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    timeout: 3.0
    disabled: false

  - name: bing
    engine: bing
    shortcut: b
    timeout: 3.0
    disabled: false

  - name: yahoo
    engine: yahoo
    shortcut: y
    timeout: 3.0
    disabled: false

outgoing:
  request_timeout: 3.0
  max_request_timeout: 10.0
  pool_connections: 100
  pool_maxsize: 100
  enable_http2: true
  verify: true
  max_redirects: 5
  retries: 1
  proxies:
    http: false
    https: false
  using_tor_proxy: false
  local_ips_whitelist: []
  useragent_suffix: "DeepSearch/1.0"

redis:
  url: false

ui:
  static_path: ""
  templates_path: ""
  default_theme: simple
  default_locale: "en"
  results_on_new_tab: false
  infinite_scroll: false
  center_alignment: false
  donation_url: false
  issue_url: false
  public_instances: false
  enable_metrics: false 